"""Add profile fields

Revision ID: 0048d024f293
Revises: 
Create Date: 2026-08-14 12:23:00.807773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0048d024f293'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('high_school', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about')
        batch_op.drop_column('github')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('high_school')

    # ### end Alembic commands ###
