"""Add updated_at to problems

Revision ID: 6c7e08e3776c
Revises: 928d8827600c
Create Date: 2026-08-19 20:24:45.359061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c7e08e3776c'
down_revision = '928d8827600c'
branch_labels = None
depends_on = None


def upgrade():

    # updated_at există deja în DB, deci NU o mai adăugăm

    with op.batch_alter_table("problems") as batch_op:

        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False
        )

    # Toate problemele existente primesc aceeași dată
    # ca și created_at, dar doar unde updated_at e NULL
    op.execute(
        "UPDATE problems SET updated_at = created_at WHERE updated_at IS NULL"
    )

    with op.batch_alter_table("problems") as batch_op:

        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(),
            nullable=False
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
