"""Simplify problem model

Revision ID: 84f33487e416
Revises: 305096bff941
Create Date: 2026-08-24 18:40:44.356976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f33487e416'
down_revision = '305096bff941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notebook_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('starter_archive', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ground_truth_file', sa.String(length=255), nullable=True))
        batch_op.drop_column('output_description')
        batch_op.drop_column('examples')
        batch_op.drop_column('statement')
        batch_op.drop_column('evaluation')
        batch_op.drop_column('input_description')
        batch_op.drop_column('short_description')
        batch_op.drop_column('constraints')
        batch_op.drop_column('hints')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hints', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('constraints', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('short_description', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('input_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('evaluation', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('statement', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('examples', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('output_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('ground_truth_file')
        batch_op.drop_column('starter_archive')
        batch_op.drop_column('notebook_file')

    # ### end Alembic commands ###
