"""Add created_at and created_by to problems

Revision ID: 928d8827600c
Revises: 022a0c5ff9dd
Create Date: 2026-08-19 20:18:06.283797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928d8827600c'
down_revision = '022a0c5ff9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
