"""Add created_at and created_by to problems

Revision ID: 928d8827600c
Revises: 022a0c5ff9dd
Create Date: 2026-08-19 20:18:06.283797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928d8827600c'
down_revision = '022a0c5ff9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
